### ISSUE TITLE
Generate interface for easer unit testing

### ISSUE THREAD

**Issue by anjmao** [hooklift/gowsdl#104]
Hi, it would be really nice if gowsdl could generate public service interface. https://github.com/fiorix/wsdl2go does that. 

```go
// public interface
type SoapService interface {
	Ping(PingRequest) PingResponse
}

// public 
func NewSoapService(...) SoapService {
	return &soapService{...}
}

// private
type soapService struct {

}
```

I could my PR for it.

**Comment by c4milo** [comment]
@anjmao, agreed. Is this because you want to mock the services in your tests?

**Comment by anjmao** [comment]
@c4milo Yes, I'm using gomock to autogenerate mocks, but since there is no interface I could only create my own interface and proxy gowsdl service. I will make a PR, hope it will be done today :)

**Comment by anjmao** [comment]
fixed with https://github.com/hooklift/gowsdl/commit/193c95ad2f469c5f82a8ad8fca580a159dc85a60

**Comment by pardedetalenta** [comment]
> @c4milo Yes, I'm using gomock to autogenerate mocks, but since there is no interface I could only create my own interface and proxy gowsdl service. I will make a PR, hope it will be done today :)

hi @anjmao , kindly help me to know how to create mock for the service? any example?
