### ISSUE TITLE
Suggestions for more idiomatic code

### ISSUE THREAD

**Issue by anjmao** [hooklift/gowsdl#106]
Hi,

1. Current api could be improved a bit. Example from current generated soap client.

```go
func NewSOAPClient(url string, insecureSkipVerify bool, auth *BasicAuth) *SOAPClient {
	tlsCfg := &tls.Config{
		InsecureSkipVerify: insecureSkipVerify,
	}
	return NewSOAPClientWithTLSConfig(url, tlsCfg, auth)
}

func NewSOAPClientWithTLSConfig(url string, tlsCfg *tls.Config, auth *BasicAuth) *SOAPClient {
	return &SOAPClient{
		url:    url,
		tlsCfg: tlsCfg,
		auth:   auth,
	}
}
```

This is not very friendly api to use. Instead it's a common practice in go to use ...option. These 2 functions which are both not flexible can be refactored to

```go
func NewSOAPClient(opt ...SOAPOption) *SOAPClient {
	opts := defaultSOAPOptions
	for _, o := range opt {
		o(&opts)
	}
        return &SOAPClient{
		url:    opts.url,
		tlsCfg: opts.tlsCfg,
		auth:   opts.auth,
	}
}
```

Usage

```go
client := NewSOAPClient(
       gowsdl.URL('myservice.asmx'), 
       gowsdl.TLSCfg(....),
       gowsdl.Auth(...),
       gowsdl.SothingElse(...)
)
```
It will also allow to stay backwards compatible add be able to add new config options in the feature.

2. It's not possible to set global request headers, for example there is hardcoded `req.Header.Set("User-Agent", "gowsdl/0.1")`, but service which I want to call checks if user-agent is `name-x` otherwise to throws unauthorised fault error.
This can be implemented simply by having `SOAPOption` RequestHeaders.

3. There are log.Println statments inside code https://github.com/hooklift/gowsdl/blob/master/soap_tmpl.go#L268. This is bad when using docker and kubernetes. For example in my services all stdout logs a automatically pushed elastic search(kibana). In general print statements should be used only on some tracing mode enabled.

**Comment by c4milo** [comment]
I welcome all the above improvements @anjmao.

**Comment by anjmao** [comment]
Here is some work I already did in my branch https://github.com/trackforce/gowsdl/tree/refactor-soap-client.

- Removed soap_tmp.go and moved soap client to separate package.
- Added example folder with usages https://github.com/trackforce/gowsdl/blob/refactor-soap-client/example/example.go

Idea is to pass soap client to each generated service so there is no complex call logic inside generated files.
I will probably finish on Monday.

**Comment by c4milo** [comment]
@anjmao I like those changes. We should probably initialize a go module for this library and tag it before introducing these new changes.

**Comment by anjmao** [comment]
@c4milo I Agree for modules. I'm currently testing library with my changes by calling some of our production soap services, but I'm getting XML marshal/unmarshal errors. I added comment in my PR.
