### ISSUE TITLE
Prepare Release v1.0.0

### ISSUE THREAD

**Issue by anjmao** [hooklift/gowsdl#108]
TODO for v1.0.0 release which is breaking change.

- [x]  Add mod file for go modules support
- [ ]  Fix issue https://github.com/hooklift/gowsdl/issues/38 which requires to change code generation and use custom DateTime struct instead of built time.Time

@c4milo What do you think?

**Comment by c4milo** [comment]
Sorry for the very late response here. This looks good to me.

**Comment by moihn** [comment]
Is now a good time to have this new release version?

**Comment by c4milo** [comment]
@moihn, I think so. I will tag a release later today.

**Comment by moihn** [comment]
Hi, any progress for this new release tag? the current v 0.4.0 is quite old and a default "go get github.com/hooklift/gowsdl" will not give us the new features. Otherwise, we need to always use "go get github.com/hooklift/gowsd/...@master".

**Comment by c4milo** [comment]
@moihn, sorry for the delay, I just pushed v0.5.0. Thanks!
