### ISSUE TITLE
mock for service

### ISSUE THREAD

**Issue by pardedetalenta** [hooklift/gowsdl#110]
hi @anjmao , kindly help me to know how to create mock for the service? any example? thank you :)

_Originally posted by @pardedetalenta in https://github.com/hooklift/gowsdl/issues/104#issuecomment-434924009_

**Comment by pardedetalenta** [comment]
Oh, sorry. I mean the test for the service using that mock that we've been generated using that mockgen. I kind of confused, cause it gives me missing call to the mock that I've been generated before. It can't call the service

**Comment by anjmao** [comment]
@pardedetalenta If you look at https://github.com/hooklift/gowsdl/blob/master/example/example.go#L14 each soap service already returns interface, you just need to mock that interface under your code which you are testing.

**Comment by anjmao** [comment]
Closing this, feel free to create new issue if you have any problems.
