### ISSUE TITLE
Allow passing context

### ISSUE THREAD

**Issue by fdeddys** [hooklift/gowsdl#111]
I create wsdl client, but with timeout

If i fill 1ms its work i think, but if other value , its not working and no timeout

my code
client := soap.NewClient(url, soap.WithTimeout(1*time.Millisecond))

how i can setting to 1 s

thanks

**Comment by anjmao** [comment]
Hi, have you tried soap.WithTimeout(1*time.Second) ?

**Comment by fdeddys** [comment]
hi..
already try other duration such as time.Second, time Microsecond etc
( ex 1000 millisecond, 1000000 microsecond )
not working

**Comment by anjmao** [comment]
Hi @fdeddys 
Could you try to call you endpoint with this code, since gowsdl uses DialTimeout internally.

```go
var timeout = time.Duration(2 * time.Second)

func dialTimeout(network, addr string) (net.Conn, error) {
    return net.DialTimeout(network, addr, timeout)
}

func main() {
    transport := http.Transport{
        Dial: dialTimeout,
    }

    client := http.Client{
        Transport: &transport,
    }

    resp, err := client.Get("http://some.url")
}
```

**Comment by fdeddys** [comment]
Dear mr @anjmao 
 i'm using client from "github.com/hooklift/gowsdl/soap"

i think if your code 

resp, err := client.Get("http://some.url")
it's will use "net/http"... cmiiw..?

so my code totally like https://github.com/hooklift/gowsdl/blob/master/example/example.go
client := soap.NewClient(url)
then client.Call(...)
any idea using this method? or can you share other article?

**Comment by anjmao** [comment]
@fdeddys Hi, how are you testing dial timeout? Do you have some endpoint which takes more that 1ms to dial and you are not able to call it?

**Comment by fdeddys** [comment]
hi @anjmao 
ok, i will try it, it's update in soap.go ?
we have local test server and its take about 2 - 3 second until get response. 
First i try put timeout 1 second, but my app still waiting until got response from test server


after add func dialTimeout, i will inform you

**Comment by fdeddys** [comment]
hi @anjmao 

I change in soap.go, but  its still not working

`var timeout = time.Duration(2 * time.Second)`

` func (s *Client) Call(soapAction string, request, response interface{}) error {`
` ... `
`tr := &http.Transport{`
`		TLSClientConfig: s.opts.tlsCfg,`
`		Dial: func(network, addr string) (net.Conn, error) {`
`			return net.DialTimeout(network, addr, timeout)`
`			//s.opts.timeout)`
`		},`
`	}`

**Comment by anjmao** [comment]
@fdeddys Hi, it looks that the problem you have is not related to dial timeout. You can establish connection quickly but you service can be slow to respond. This can be handled using `context` package

general example using http client
```go
package main

import (
   "fmt"
   "context"
   "net/http"
)

func main() {
	// Create a new context
	// With a deadline of 100 milliseconds
	ctx := context.Background()
	ctx, _ = context.WithTimeout(ctx, 100*time.Millisecond)

	// Make a request, that will call the google homepage
	req, _ := http.NewRequest(http.MethodGet, "http://google.com", nil)
	// Associate the cancellable context we just created to the request
	req = req.WithContext(ctx)

	// Create a new HTTP client and execute the request
	client := &http.Client{}
	res, err := client.Do(req)
	// If the request failed, log to STDOUT
	if err != nil {
		fmt.Println("Request failed:", err)
		return
	}
	// Print the statuscode if the request succeeds
	fmt.Println("Response received, status code:", res.StatusCode)
}
```

Unfortunately gowsdl doesn't support passing context.
