### ISSUE TITLE
Soap folder is missing from latest release (0.3.0)

### ISSUE THREAD

**Issue by gkiriakidis** [hooklift/gowsdl#117]
I am not sure if this is an issue or not :), 
but in your latest release, the "soap" folder is missing.
https://github.com/hooklift/gowsdl/tree/v0.3.0

When I am trying to build a project (by using go modules, outside GOPATH):
```
$ go build -v .
go: extracting github.com/hooklift/gowsdl v0.3.0
go: finding github.com/hooklift/gowsdl/soap latest
Fetching https://github.com?go-get=1
Parsing meta tags from https://github.com?go-get=1 (status code 200)
ourFile.go:19:2: unknown import path "github.com/hooklift/gowsdl/soap": cannot find module providing package github.com/hooklift/gowsdl/soap
```

**Comment by anjmao** [comment]
Hi @gkiriakidis, sorry for that, I probably did something wrong while creating a release. I added new tag https://github.com/hooklift/gowsdl/tree/v0.3.1
