### ISSUE TITLE
Support overriding RoundTripper/Transport

### ISSUE THREAD

**Issue by iszak** [hooklift/gowsdl#125]
I have a use case where I want to override the `http.Transport` to a custom `http.RoundTripper` which `http.Client` expects. This is so I can create metrics around the SOAP HTTP requests.

Unfortunately, I am not sure about adding an option, such as `WithRoundTripper` or `WithTransport` as this will then require checking that `WithTLSHandshakeTimeout`, `WithTLS`, `WithTimeout` has not already been set as these options would not likely be supported 

I can imagine this will expand to cover all of Transport's options, in which case I don't see much benefit unless we expect to swap out the HTTP client in the future. I'm happy to implement the desired solution, as I require it, but some guidance on preferred approach would be ideal.

**Comment by anjmao** [comment]
Hi @iszak, I think you can add option `WithHTTPClient` which allows to fully replace not only http.Transport but also underlying http client.  WithTLS, WithTimeout will not work, but adding note to a readme may be ok.

Ideally I would rather remove WithTLS, WithTLS helpers and just use WithHTTPClient if I need any custom configuration on http client.

**Comment by iszak** [comment]
@anjmao I've created a pull request to override the HTTP Client. Feedback would be appreciated. I decided to use an interface in case someone else wanted to use a different implementation, for whatever reason. I'm not sure if it is worth it or not especially considering the arguments/return types are still of type http.Request/Response
