### ISSUE TITLE
service.client.CallContext undefined

### ISSUE THREAD

**Issue by madshov** [hooklift/gowsdl#136]
`CallContext()` does not exist. I'm using version 0.3.1

**Comment by zaddok** [comment]
I have this problem as well. Is it a new bug? I wonder if we bump back a few versions we can work around this?

**Comment by zaddok** [comment]
It appears the problem is that the most recent go module tag 0.3.1 is incompatible with the version you get with "git clone".

**Comment by gocustomized** [comment]
Is this ever getting a new release so we can use it with a dependency manager ? Or should i just clone it into my project and replace it from go.mod/Gopkg ?

**Comment by toyo-iacob** [comment]
Is this ever getting a new release so we can use it with a dependency manager ? Or should i just clone it into my project and replace it from go.mod/Gopkg ?

**Comment by c4milo** [comment]
I can look into it tonight.

**Comment by c4milo** [comment]
I just pushed v0.4.0.
