### ISSUE TITLE
HTTP error codes not handled

### ISSUE THREAD

**Issue by zaddok** [hooklift/gowsdl#140]
If the webserver returns a http error message then this is not reported or reflected in response. i.e. if the Webserver returns HTTP 404, the error is not reported back to the client.

**Comment by mndailey** [comment]
I added the following to 

commit: 4acf24e0e4ce71757ac6c5c115201b6050aa96d5 
file: soap/soap.go 
line: 345

	// If status of response is other than 2xx then return error indication
	if res.StatusCode < 200 || res.StatusCode > 299 {
		return fmt.Errorf("HTTP Status: %d - %s", res.StatusCode, http.StatusText(res.StatusCode))
	}

Alternately here is the diff:

diff --git a/soap/soap.go b/soap/soap.go
index f35faba..a4ce01e 100644
--- a/soap/soap.go
+++ b/soap/soap.go
@@ -343,6 +343,11 @@ func (s *Client) call(ctx context.Context, soapAction string, request, response
        }
        defer res.Body.Close()
 
+       // If status of response is other than 2xx then return error indication
+       if res.StatusCode < 200 || res.StatusCode > 299 {
+               return fmt.Errorf("HTTP Status: %d - %s", res.StatusCode, http.StatusText(res.StatusCode))
+       }
+
        respEnvelope := new(SOAPEnvelope)
        respEnvelope.Body = SOAPBody{Content: response}

**Comment by nikolay-turpitko** [comment]
@mndailey Wrong commit reference? I don't see anything similar to your change in that commit.

Also, I think, it'd be helpful to return some struct with status code inside it to be able to cast it to the type and to avoid parsing error msg in the calling code.

For example, in the case I want to react on 503 error and re-try the request later, I'll need to extract error code from the error message. If someone later would change error msg format, my code will break. I'd prefer to do something like below (in the client code):

```
if err, ok := err.(soap.Error); ok && err.BadStatusCode() && err.StatusCode() == 503 {
    // ...
}
```
Or, at least, just

```
if err, ok := err.(soap.BadStatusCodeError); ok && err.StatusCode == 503 {
    // ...
}
```
In the first case it could be more generic error and have methods to check other wrapped error cases, like `err.MarshallingError()` (like https://golang.org/pkg/net/#Error).

**Comment by ninthclowd** [comment]
I think this issue can be closed now. After #197 was merged, you can now retrieve the status code and response body with:

```go
if httpError, ok:=err.(*soap.HTTPError); ok {
 log.Printf("HTTP Status %d: %s", httpError.StatusCode, string(httpError.ResponseBody))
}
```
