### ISSUE TITLE
soup request generated request body without any prefix name space in tags

### ISSUE THREAD

**Issue by robatipoor** [hooklift/gowsdl#175]
for example this is correct and hassle-free request body 
```
<soapenv:Envelope xmlns:soapenv="...envelope/" xmlns:inv="...invservices" xmlns:crm="...crmheader" xmlns:com="...common">
    <soapenv:Header />
    <soapenv:Body>
      ...
    </soapenv:Body>
</soapenv:Envelope>
```
but generated soup request body is 
```
<Envelope>
    <Body>
       ....
    </Body>
</Envelope>
```
i get the error response failed to query please help me

**Comment by koenpunt** [comment]
I have the same issue. Is there a way to get the prefixes?

**Comment by MKITConsulting** [comment]
This is fixed with PR https://github.com/hooklift/gowsdl/pull/201 and already merged.

**Comment by robatipoor** [comment]
thanks
