### ISSUE TITLE
local error: tls: no renegotiation

### ISSUE THREAD

**Issue by SantoshSah** [hooklift/gowsdl#189]
Hi,

`gowsdl` throwing error `local error: tls: no renegotiation` even after using flag `-i` for wsdl `https://services.360lifecycle.co.uk/leadservice.svc?wsdl` and `https://services.360lifecycle.co.uk/leadservice.svc?singlewsdl`. Please see below screenshot.

<img width="1191" alt="gowsdl-error" src="https://user-images.githubusercontent.com/2204972/106000788-52e66c80-60d7-11eb-9dd8-624ed6c295a7.png">

**Comment by c4milo** [comment]
hmm, the TLS implementation in Go has TLS renegotiation disabled by default. To enable it, one has to set the `Renegotiation` field as such: 

```
config := &tls.Config{
    Renegotiation: tls.RenegotiateFreelyAsClient,
}
```

**Comment by SantoshSah** [comment]
Thanks. I had installed using homebrew and default installation was not working. When i compiled binary with above modification, it worked.
