### ISSUE TITLE
generated code invalid if duplicate complexTypes

### ISSUE THREAD

**Issue by natebrennand** [hooklift/gowsdl#19]
excerpt from example here: https://gist.github.com/natebrennand/1c57291e10bed537b10b

`ArrayOfInteger` is declared twice. If a complex type is declared multiple times it seems that it is generated twice too. FWIW, the server seems to utilize the first declaration, not the subsequent ones.
Would be great if this edge case was handled.

Thanks for the awesome tool!

**Comment by c4milo** [comment]
I will look into this. Thanks!

**Comment by c4milo** [comment]
"...no complex type definition can have the same name as another simple or complex type definition. " -- 
http://www.w3.org/TR/xmlschema-1/#Complex_Type_Definitions

I'm going to consider this as a won't fix issue. The reason being is that your schema does not comply with the spec, it is an issue with the schema not with gowsdl.
