### ISSUE TITLE
Generates incorrect code for `complexType`s that extend built-in types

### ISSUE THREAD

**Issue by ieure** [hooklift/gowsdl#204]
I generated client code for Workday's SOAP API — they're a popular HR/Payroll/Time & Attendance service.  Unfortunately, gowsdl generates incorrect output for many [`complexType` definitions](https://www.w3.org/TR/xmlschema-1/#Complex_Type_Definition_details) that extend built-ins; in my case, an extension of `string` to add a `type` attribute.

For this bit of WSDL:

      <xsd:complexType name="WorkerObjectIDType">
        <xsd:annotation>
          <xsd:documentation>Contains a unique identifier for an instance of an object.</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleContent>
          <xsd:extension base="xsd:string">
            <xsd:attribute name="type" type="wd:WorkerReferenceEnumeration" use="required">
              <xsd:annotation>
                <xsd:documentation>The unique identifier type. Each "ID" for an instance of an object contains a type and a value. A single instance of an object can have multiple "ID" but only a single "ID" per "type".</xsd:documentation>
              </xsd:annotation>
            </xsd:attribute>
          </xsd:extension>
        </xsd:simpleContent>
      </xsd:complexType>

gowsdl outputs:

    type WorkerObjectIDType string

…which is incorrect.  The `type` attribute is ignored, and since it's required, no request gowsdl generates can be processed.  I'm not sure what the serialized output should look like, but the correct Go code would be something like:

```go
type WorkerObjectIDType struct {
    Type string
    Value string
}
```

Just to make sure I wasn't wrong about this, I used `wsimport` to generate Java code; it produces what I'd expect:

```java
public class WorkerObjectIDType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "type", namespace = "urn:com.workday/bsvc", required = true)
    protected String type;

    …
}
```

**Comment by c4milo** [comment]
Hm, yes, that would be a bug. Thanks for the clear report!
