### ISSUE TITLE
Line feeds in WSDL

### ISSUE THREAD

**Issue by notzippy** [hooklift/gowsdl#21]
Hi

I found that if the wsdl:documentation had line feeds in it the generated code would get messed up like the following

		// Error can be either of the following types:
		// 
		//   - ValidationFaultFault 
		//
				GetFullEstimate
				@param request GetFullEstimateRequest
				@return GetFullEstimateResponse
		func (service *EstimatingServiceContract) GetFullEstimate (request *GetFullEstimateRequestContainer) (*GetFullEstimateResponseContainer, error) {

Relevant WSDL source

		<wsdl:operation name="GetFullEstimate">
			<wsdl:documentation>
				GetFullEstimate
				@param request GetFullEstimateRequest
				@return GetFullEstimateResponse
			</wsdl:documentation>

**Comment by c4milo** [comment]
Closed by #22
