### ISSUE TITLE
Empty strings in enums results in broken code

### ISSUE THREAD

**Issue by bensijons** [hooklift/gowsdl#236]
If a WSDL file has an enumeration with an empty string value, gowsdl will currently generate broken go code. 

For example:

```xml
<simpleType name="DriveTrain">
    <restriction base="string">
        <enumeration value="" />
        <enumeration value="Front Wheel Drive" />
        <enumeration value="Rear Wheel Drive" />
        <enumeration value="All Wheel Drive" />
        <enumeration value="Four Wheel Drive" />
    </restriction>
</simpleType>
```

This XML will generate the following go code:
<img width="546" alt="Screenshot 2022-03-15 at 21 33 26" src="https://user-images.githubusercontent.com/35707048/158477080-66412474-e71a-4c13-914e-6cc081ecfbc3.png">

Since the enum value is being used as part of the name of the const generated, the empty string value will return a const name that is the same as the name of the type generated (In this case DriveTrain)

**Comment by c4milo** [comment]
Good catch @bensijons! Thanks!
