### ISSUE TITLE
Inconsistent behavior with names with underscores

### ISSUE THREAD

**Issue by JoopClaireIT** [hooklift/gowsdl#29]
Link to test on: http://planitonline.dyndns.org/planitonline/api.wso

When using gives error on line 74, not identified
Removing the underscore on that line solves the problem

**Comment by c4milo** [comment]
@JoopClaireIT, I'm not sure I'm following. Can you provide a code example?

**Comment by JoopClaireIT** [comment]
when I run gowsdl on the given link and I import it in a new project and try to compile, it gives a compiler error with an inconsistency between the same name with and without an underscore.
