### ISSUE TITLE
time.Time parsing error

### ISSUE THREAD

**Issue by trapias** [hooklift/gowsdl#31]
After generating a class to access the VIES web service for EU VAT validation service I get an error when class tries to parse a good response:

	Error: parsing time "2015-08-05+02:00" as "2006-01-02T15:04:05Z07:00": cannot parse "+02:00" as "T"

The field generating the error is a time.Time field both in CheckVatResponse and CheckVatApproxResponse structs:

	RequestDate time.Time `xml:"requestDate,omit empty"`

If I convert the field to a string, I can successfully access the service as reported in issue #30.
The response from the service contains a "RequestDate" field filled in like this:

		RequestDate:2015-08-05+02:00

which generates the error above.

**Comment by c4milo** [comment]
I'm going to close this as it seems to be related to the WSDL giving an invalid datetime type. Please feel free to reopen if you feel otherwise.
