### ISSUE TITLE
Choice elements not being generated

### ISSUE THREAD

**Issue by sanbornm** [hooklift/gowsdl#34]
It looks like elements wrapped in the choice tag are not being generated.  I see there are some test fixtures with choice tags but I don't see any tests for them.  I tried troubleshooting this myself but was unsuccessful.  Can you try generating a wsdl with choice elements or point me in the right direction for adding support for these.

It looks like the ec2 fixture has choice elements.

Thanks!

**Comment by c4milo** [comment]
Confirmed. It happens with choice elements nested within sequence elements.

**Comment by sanbornm** [comment]
Once 2e8ea25 is merged in this can probably be closed.  I am not sure this is the best solution but it does fix the issue.

**Comment by c4milo** [comment]
This is not the more generic solution considering that sequence elements can also have: `(element|group|choice|sequence|any)*`. But, let's keep it simple and only for nested choice elements for now.  This landed in https://github.com/hooklift/gowsdl/commit/4e0b9fe0dc557f586dacca7cbdc4c2afe683524e
