### ISSUE TITLE
Support for imports

### ISSUE THREAD

**Issue by sanbornm** [hooklift/gowsdl#41]
It looks like imports are not being pulled into the schema.  They are specified on the XSDSchema struct but never used.

**Comment by sanbornm** [comment]
This is partially implemented in the support-for-imports branch.  Still needs support for external files.

I also noticed that includes ONLY support external files, not local.

**Comment by danielkwinsor** [comment]
Looks like this branch supports XSD imports, and I would like to see imports of wsdls too.
