### ISSUE TITLE
Generate code syntax error: unexpected comma

### ISSUE THREAD

**Issue by ruly1000** [hooklift/gowsdl#64]
Trying to generate code for the Billing Tree Payrazr WSDL located here:

[https://staging.mypayrazr.com/ApiServiceWeb/SimpleApiService.svc?wsdl](https://staging.mypayrazr.com/ApiServiceWeb/SimpleApiService.svc?wsdl)

func returns are invalid, pointer ref "*" with no type, example of one generated func: 

		func (service *ISimpleApiService) SubmitCardSale () (*, error) {
			response := new()
			err := service.client.Call("http://tempuri.org/ISimpleApiService/SubmitCardSale", nil, response)
			if err != nil {
				return nil, err
			}

			return response, nil
		}

**Comment by bobbytables** [comment]
I'm having this as well, could you point my in the direction for possibly fixing this and contributing back?

**Comment by bobbytables** [comment]
To add, I'm doing the ambitious task of using `gowsdl` to generate Go from the NetSuite WSDL: https://webservices.netsuite.com/wsdl/v2016_2_0/netsuite.wsdl

**Comment by ruly1000** [comment]
The problem ended up being that our WSDL was SOAP v1.2, gowsdl only supports SOAP v1.1 so we could not use it, ended up manually defining structs and using encoding/xml to marshall/unmarshall them.
