### ISSUE TITLE
onvif: Can't convert. Go file

### ISSUE THREAD

**Issue by CodyGuo** [hooklift/gowsdl#67]
http://www.onvif.org/Documents/Specifications.aspx
ONVIF WSDL and XML Schemas Specifications
...
http://www.onvif.org/onvif/ver10/events/wsdl/event.wsdl
...

gowsdl.exe event.wsdl
🍀  Downloading external schema location http://www.w3.org/20
05/08/addressing/ws-addr.xsd
🍀  Downloading external schema location http://docs.oasis-op
en.org/wsn/t-1.xsd
🍀  Downloading external schema location http://docs.oasis-op
en.org/wsn/b-2.xsd
🍀  708:2: expected type, found 'const' (and 3 more errors)

**Comment by CodyGuo** [comment]
gowsdl -o deviceio.go deviceio.wsdl
🍀  43:2: expected type, found 'const' (and 2 more errors)

**Comment by realmfoo** [comment]
`gowsdl` doesn't understand `<union>`:
```
        <xs:simpleType name="RelationshipTypeOpenEnum">
                <xs:union memberTypes="tns:RelationshipType xs:anyURI"/>
        </xs:simpleType>
```

**Comment by bmurray** [comment]
This works correctly now. Don't know since when, but this issue can be closed.
