### ISSUE TITLE
coulnd't parse nested list type

### ISSUE THREAD

**Issue by litan1106** [hooklift/gowsdl#72]
**example:** 
<xs:simpleType name="DeviceTypeReportFilter">
<xs:list>
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:enumeration value="Computer"/>
<xs:enumeration value="SmartPhone"/>
<xs:enumeration value="NonSmartPhone"/>
<xs:enumeration value="Tablet"/>
</xs:restriction>
</xs:simpleType>
</xs:list>
</xs:simpleType>

**result:** 

type DeviceTypeReportFilter *

const ()

**expected:** 

type DeviceTypeReportFilter string

const (
	DeviceTypeReportFilterComputer      DeviceTypeReportFilter = "Computer"
	DeviceTypeReportFilterSmartPhone    DeviceTypeReportFilter = "SmartPhone"
	DeviceTypeReportFilterNonSmartPhone DeviceTypeReportFilter = "NonSmartPhone"
	DeviceTypeReportFilterTablet        DeviceTypeReportFilter = "Tablet"
)

**Comment by c4milo** [comment]
hey @litan1106, why did you close it?
