### ISSUE TITLE
tries to include WSDL if impts.SchemaLocation is blank

### ISSUE THREAD

**Issue by pnhowe** [hooklift/gowsdl#76]
resolveXSDExternals will attempt to resolve the WSDL file it's self if on of schema.Imports is empty.

`if len( impts.SchemaLocation) < 1 { continue }`

between line 236 and 237 worked for me, in gowsdl.go

**Comment by senseijack** [comment]
Thanks, I just ran into the same problem and this fixed it.

**Comment by c4milo** [comment]
A PR is always appreciated. :)
